//! Unified gateway process abstraction.
//!
//! Defines the common entrypoint and envelope types shared by all gateway
//! implementations across workspaces (llmboot, microvm, etc.).
//!
//! ## Pattern
//!
//! ```text
//! InputRequest<Req>  →  Gateway::process()  →  GatewayResult<OutputResponse<Resp>>
//! ```
//!
//! Each workspace defines its own `Req` / `Resp` domain types and implements
//! `Gateway<Req, Resp>`.  Common concerns (request ID, timestamp, duration,
//! status) live in the envelope so implementations do not re-invent them.

use std::collections::HashMap;

use async_trait::async_trait;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::api::types::{GatewayError, GatewayResult, HealthCheck};
use crate::core::pipeline::Pipeline;

// ============================================================================
// Request envelope
// ============================================================================

/// Metadata attached to every inbound request.
///
/// Generated by callers (or auto-populated via [`RequestMetadata::new`]).
/// The `request_id` propagates through MDC logging so all downstream log
/// lines are correlated to the originating call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequestMetadata {
    /// Unique identifier for this request (UUID v4).
    pub request_id: String,
    /// Optional caller-provided session identifier.
    pub session_id: Option<String>,
    /// Wall-clock time the request was created.
    pub timestamp: DateTime<Utc>,
    /// Arbitrary key-value labels for routing, observability, etc.
    pub labels: HashMap<String, String>,
}

impl RequestMetadata {
    /// Create with a fresh UUID request ID and current timestamp.
    pub fn new() -> Self {
        Self {
            request_id: uuid::Uuid::new_v4().to_string(),
            session_id: None,
            timestamp: Utc::now(),
            labels: HashMap::new(),
        }
    }

    /// Attach a session ID (builder-style).
    pub fn with_session(mut self, session_id: impl Into<String>) -> Self {
        self.session_id = Some(session_id.into());
        self
    }

    /// Attach a label (builder-style).
    pub fn with_label(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.labels.insert(key.into(), value.into());
        self
    }
}

impl Default for RequestMetadata {
    fn default() -> Self {
        Self::new()
    }
}

/// Typed gateway request: domain payload wrapped in common metadata.
///
/// # Example
///
/// ```rust,ignore
/// // LLMBoot
/// let req = InputRequest::new("Write hello world".to_string());
///
/// // Microvm
/// let req = InputRequest::new(VmConfig { .. });
/// ```
#[derive(Debug, Clone)]
pub struct InputRequest<P> {
    /// Domain-specific request payload.
    pub payload: P,
    /// Common request metadata (ID, session, timestamp, labels).
    pub metadata: RequestMetadata,
}

impl<P> InputRequest<P> {
    /// Wrap a payload with auto-generated metadata.
    pub fn new(payload: P) -> Self {
        Self {
            payload,
            metadata: RequestMetadata::new(),
        }
    }

    /// Wrap a payload with caller-supplied metadata.
    pub fn with_metadata(payload: P, metadata: RequestMetadata) -> Self {
        Self { payload, metadata }
    }
}

// ============================================================================
// Response envelope
// ============================================================================

/// Terminal status of a processed request.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProcessStatus {
    /// Processing completed and the response was delivered.
    Success,
    /// Processing was short-circuited before reaching the backend
    /// (e.g., guardrail rejection, auth failure, rate limit).
    Blocked,
    /// Processing was attempted but the backend returned an error.
    Failed,
}

/// Metadata attached to every gateway response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResponseMetadata {
    /// Mirrors `InputRequest::metadata.request_id` for correlation.
    pub request_id: String,
    /// Wall-clock processing time from entry to exit.
    pub duration_ms: u64,
    /// Final outcome of the request.
    pub status: ProcessStatus,
}

/// Typed gateway response: domain content wrapped in common metadata.
#[derive(Debug, Clone)]
pub struct OutputResponse<R> {
    /// Domain-specific response payload.
    pub payload: R,
    /// Common response metadata (ID, duration, status).
    pub metadata: ResponseMetadata,
}

impl<R> OutputResponse<R> {
    /// Construct a successful response.
    pub fn ok(request_id: impl Into<String>, duration_ms: u64, payload: R) -> Self {
        Self {
            payload,
            metadata: ResponseMetadata {
                request_id: request_id.into(),
                duration_ms,
                status: ProcessStatus::Success,
            },
        }
    }

    /// Construct a blocked response (request rejected before reaching backend).
    pub fn blocked(request_id: impl Into<String>, duration_ms: u64, payload: R) -> Self {
        Self {
            payload,
            metadata: ResponseMetadata {
                request_id: request_id.into(),
                duration_ms,
                status: ProcessStatus::Blocked,
            },
        }
    }
}

// ============================================================================
// Pipeline stage markers
// ============================================================================

/// Marker trait for types that are safe to send through gateway pipeline request stages.
///
/// Implement this on your consumer-defined pipeline request type to satisfy
/// the [`PipelineGateway`] bound on `PReq`.
///
/// ```rust,ignore
/// struct MyPipelineReq { raw: String }
/// impl PipelineReq for MyPipelineReq {}
/// ```
pub trait PipelineReq: Send + Sync + 'static {}

/// Marker trait for types that are safe to send through gateway pipeline response stages.
///
/// Implement this on your consumer-defined pipeline response type to satisfy
/// the [`PipelineGateway`] bound on `PResp`.
///
/// ```rust,ignore
/// struct MyPipelineResp { content: String }
/// impl PipelineResp for MyPipelineResp {}
/// ```
pub trait PipelineResp: Send + Sync + 'static {}

// ============================================================================
// Gateway trait (object-safe public contract)
// ============================================================================

/// Unified gateway entry point.
///
/// Object-safe — consumers hold `Arc<dyn Gateway<Req, Resp>>`.
///
/// | Workspace | Req | Resp |
/// |-----------|-----|------|
/// | llmboot   | `String`    | `GatewayResponse` |
/// | microvm   | `VmConfig`  | `VmResult`        |
///
/// Implement via [`PipelineGateway`] to get `process()` for free.
#[async_trait]
pub trait Gateway<Req, Resp>: Send + Sync
where
    Req: Send + 'static,
    Resp: Send + 'static,
{
    /// Process a single request end-to-end.
    async fn process(
        &self,
        request: InputRequest<Req>,
    ) -> GatewayResult<OutputResponse<Resp>>;

    /// Return the current health of this gateway instance.
    async fn health_check(&self) -> GatewayResult<HealthCheck>;
}

// ============================================================================
// PipelineGateway trait (implementor contract)
// ============================================================================

/// Strengthened gateway contract for pipeline-based implementations.
///
/// Implementors supply three things:
///
/// 1. `pipeline()` — a pre-built [`Pipeline`] for their domain
/// 2. `into_pipeline_req()` — converts `InputRequest<Req>` → `PReq`
/// 3. `into_response()` — converts `PResp` → `OutputResponse<Resp>`
///
/// In exchange, [`process_via_pipeline()`](Self::process_via_pipeline) is
/// provided, handling request correlation, wall-clock timing, and MDC log
/// context.  Call it from `Gateway::process` to reduce it to one line:
///
/// ```rust,ignore
/// async fn process(&self, request: InputRequest<Req>) -> GatewayResult<OutputResponse<Resp>> {
///     self.process_via_pipeline(request).await
/// }
/// ```
///
/// # Object Safety
///
/// NOT object-safe (static conversion methods, generic parameters).
/// Use [`Gateway<Req, Resp>`] as the public-facing trait object.
#[async_trait]
pub trait PipelineGateway<Req, Resp, PReq, PResp>: Gateway<Req, Resp>
where
    Req: Send + 'static,
    Resp: Send + 'static,
    PReq: PipelineReq,
    PResp: PipelineResp,
{
    /// The pre-built pipeline. Called on every [`process_via_pipeline`](Self::process_via_pipeline) invocation.
    fn pipeline(&self) -> &dyn Pipeline<PReq, PResp, GatewayError>;

    /// Convert an inbound envelope into the pipeline's concrete request type.
    fn into_pipeline_req(request: InputRequest<Req>) -> PReq;

    /// Convert the pipeline's concrete response into the outbound envelope.
    ///
    /// `request_id` and `duration_ms` are measured by [`process_via_pipeline`](Self::process_via_pipeline)
    /// and passed here for inclusion in [`ResponseMetadata`].
    fn into_response(
        resp: PResp,
        request_id: String,
        duration_ms: u64,
    ) -> GatewayResult<OutputResponse<Resp>>;

    /// Execute the pipeline end-to-end with request correlation, timing, and MDC context.
    ///
    /// This is the provided method — delegate `Gateway::process` here.
    async fn process_via_pipeline(
        &self,
        request: InputRequest<Req>,
    ) -> GatewayResult<OutputResponse<Resp>> {
        let start = std::time::Instant::now();
        let request_id = request.metadata.request_id.clone();

        let log_ctx = mdc_logging::LogContext::builder()
            .session_id(request_id.clone())
            .build();

        mdc_logging::with_log_context(log_ctx, async {
            let pipe_req = Self::into_pipeline_req(request);
            let pipe_resp = self.pipeline().execute(pipe_req).await?;
            let duration_ms = start.elapsed().as_millis() as u64;
            Self::into_response(pipe_resp, request_id, duration_ms)
        }).await
    }
}
